# 一.ndarry
## 1.ndarry的特性
### 多维性

In [2]:
import numpy as np

# 创建零维ndarray
arr = np.array(5)
print(arr)
print(type(arr))
print('arr的维度:', arr.ndim)

5
<class 'numpy.ndarray'>
arr的维度: 0


In [5]:
# 创建一维ndarray
arr = np.array([1, 2, 3])
print(arr)
print('arr的维度:', arr.ndim)

[1 2 3]
arr的维度: 1


In [6]:

# 创建二维ndarray
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print('arr的维度：', arr.ndim)

[[1 2 3]
 [4 5 6]]
arr的维度： 2


### 同质性

In [7]:
arr = np.array([1, 'hello'])  # 不同的数据类型会被强制转换成相同的数据类型
print(arr)

arr = np.array([1, 2.5])
print(arr)

['1' 'hello']
[1.  2.5]


## 2.ndarry的属性

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print('数组的形状：', arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('元素的转置', arr.T)

[[1 2 3]
 [4 5 6]]
数组的形状： (2, 3)
数组的维度： 2
元素的个数： 6
元素的转置 [[1 4]
 [2 5]
 [3 6]]


## 3.ndarray的创建

In [12]:
# 基础创建方法
arr = np.array([1, 2, 3], dtype=np.float64)
print(arr)

[1. 2. 3.]


In [13]:
# copy
arr1 = np.copy(arr)
print(arr1)

[1. 2. 3.]


In [14]:
# 预定义形状
# 全零
arr = np.zeros((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
# 全一
arr = np.ones((2, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
# 未定义
arr = np.empty((2, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
# 填充指定值
arr = np.full((3, 4), 2026)
print(arr)

[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [18]:
# 拷贝形状,值为全零
arr1 = np.zeros_like(arr)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [19]:
# range
arr = np.arange(0, 10, 1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
# 将区间均分为 n-1 份
arr = np.linspace(0, 100, 5)
print(arr)

[  0.  25.  50.  75. 100.]


In [22]:
# 指数序列
arr = np.logspace(0, 4, 3, base=2)
print(arr)

[ 1.  4. 16.]


In [3]:
# 特殊矩阵
# 单位矩阵
arr = np.eye(3, dtype=int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [4]:
# 对角矩阵
arr = np.diag([1, 2, 3, 4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [5]:
# 随机数矩阵
# 0到1之间的随机浮点数（均匀分布）
arr = np.random.rand(2, 3)
print(arr)

[[0.35801017 0.29440763 0.67881092]
 [0.69257568 0.32146161 0.40885946]]


In [6]:
# 指定范围的随机浮点数
arr = np.random.uniform(3, 6, (2, 3))
print(arr)

[[3.66161389 4.90290365 5.34624915]
 [4.38302689 4.17271293 4.84842846]]


In [7]:
# 生成指定范围区间的随机整数
arr = np.random.randint(3, 30, (2, 3))
print(arr)

[[14  5 21]
 [23 17 21]]


In [8]:
# 生成随机数列（正态分布）
# 两边小，中间大
arr = np.random.randn(2, 3)
print(arr)

[[-0.02612629  0.53413319  0.93324208]
 [-0.85974978  1.67371273  0.21565825]]


## 4.ndarray数据类型
布尔类型 bool

整数类型  int  uint

浮点数   float

复数  complex

In [9]:
arr = np.array([1, 0, 127, 0], dtype=np.int8)
print(arr)

[  1   0 127   0]


## 5.索引与切片

In [10]:
# 一维数组的索引与切片
np.random.seed(20)
arr = np.random.randint(1, 100, 20)
print(arr)

[91 16 96 29 91 10 21 76 23 72 35 97 41 86 91 27 84 17 63 17]


In [11]:
print(arr[10])
print(arr[:])
print(arr[2:5])
print(arr[slice(2, 5, 1)])  # 同上
print(arr[(arr > 10) & (arr < 70)])  # 布尔索引

35
[91 16 96 29 91 10 21 76 23 72 35 97 41 86 91 27 84 17 63 17]
[96 29 91]
[96 29 91]
[16 29 21 23 35 41 27 17 63 17]


In [13]:
# 二维数组的索引与切片
arr = np.random.randint(1, 100, (4, 8))
print(arr)

[[ 8 99  7 27 14 76 59 26]
 [ 4 75 76 62 78 84 58 95]
 [33 11  7 76 19  4 78 18]
 [44 17 19 80 91 60 72 76]]


In [18]:
print(arr[1, 3])  # 获取元素
print(arr[0])  # 获取行
print(arr[:, 0])  # 获取列
print(arr[0][1:4])  # 对指定行切片
print(arr[2][arr[2] > 50])  # 对指定行布尔过滤


62
[ 8 99  7 27 14 76 59 26]
[ 8  4 33 44]
[99  7 27]
[76 78]


## 6.ndarray运算

In [19]:
# 算术运算
# 一维
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [20]:
# 二维
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(a + b)
print(a - b)
print(a * b)  # 按位置对应相乘
print(a / b)
print(a ** 2)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [21]:
# 数组与标量运算
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a + 3)
print(a * 3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [22]:
# 形状不同的矩阵做运算,要看能否广播
# 广播机制: 同一维度值相同,或者存在1
a = np.array([1, 2, 3])  #1*3
b = np.array([[4], [5], [6]])  #3*1
"""
a
1 2 3
1 2 3
1 2 3

b
4 4 4
5 5 5
6 6 6
"""
print(b - a)

[[3 2 1]
 [4 3 2]
 [5 4 3]]


In [23]:
# 矩阵相乘: res[i][j] = a的i行 与 b的j列 对应相乘再相加
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(a @ b)
"""
res[i][j]=sum(a[i]*b[:,j])
res[0][0] = 1*4 + 2*7 + 3*1 = 21
"""

[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


# 二.numpy中的函数
## 1.基本数学函数

In [3]:
# 平方根
arr = np.array([1, 25, 81])
print(np.sqrt(arr))

[1. 5. 9.]


In [4]:
# 自然指数
print(np.exp(1))

2.718281828459045


In [6]:
# 自然对数
print(np.log(2.718281828459045))

1.0


In [9]:
# 三角函数
print(np.sin(np.pi))
print(np.cos(np.pi))

1.2246467991473532e-16
-1.0


In [10]:
# 绝对值
arr = np.array([-1, 1, 2, -3])
print(np.abs(arr))

[1 1 2 3]


In [11]:
# 幂
print(np.power(arr, 3))

[ -1   1   8 -27]


In [12]:
# 四舍五入(.5向偶数舍入)
print(np.round([3.2, 4.5, 8.1, 9.6]))

[ 3.  4.  8. 10.]


In [13]:
# 取整
arr = np.array([1.6, 25.1, 81.7])
print(np.ceil(arr))
print(np.floor(arr))

[ 2. 26. 82.]
[ 1. 25. 81.]


In [15]:
# 检测缺失值
np.isnan([1, 2, np.nan, 3])

array([False, False,  True, False])

## 2.统计函数

In [18]:
arr = np.random.randint(1, 200, 8)
print(arr)

[147  84 198  47  62  46  85  26]


In [21]:
# 求和
print(np.sum([1, 2, 3]))

6


In [29]:
# 平均值
print(np.mean(arr))

86.875


In [30]:
# 中位数
print(np.median([1, 1, 1, 1, 1, 1, 1, 1, 1, 100]))

1.0


In [33]:
# 方差: 每个数与平均值的差平方再平均
# 标准差: 方差开方
arr1 = np.array([1, 2, 1, 2, 1, 1, 1, 2])
arr2 = np.array([1, 0, 3, 0, 0, 0, 4, 3])
print(np.mean(arr1))
print(np.mean(arr2))
# 方差
print(np.var(arr1))
print(np.var(arr2))
# 标准差
print(np.std(arr1))
print(np.std(arr2))

1.375
1.375
0.234375
2.484375
0.4841229182759271
1.5761900266148114


In [34]:
# 最值
print(arr)
# 最大值及其下标
print(np.max(arr), np.argmax(arr))
print(np.min(arr), np.argmin(arr))

[147  84 198  47  62  46  85  26]
198 2
26 7


In [39]:
# 分位数: 计算 n 满足 x% 的数小于 n
arr = np.random.randint(0, 100, 4)
print(arr)
print(np.percentile(arr, 80))

[39 87 46 88]
87.4


In [40]:
# 前缀和\前缀积
arr = np.array([1, 2, 3])
print(np.cumsum(arr))
print(np.cumprod(arr))

[1 3 6]
[1 2 6]


## 3.比较函数

In [43]:
# 大小比较
print(np.greater([3, 4, 5, 6, 7], 5))
print(np.less([3, 4, 5, 6, 7], 5))
print(np.equal([3, 4, 5, 6, 7], 5))
print(np.equal([3, 4, 5], [4, 4, 4]))

[False False False  True  True]
[ True  True False False False]
[False False  True False False]
[False  True False]


In [45]:
# 逻辑运算
print(np.logical_and([0, 1, 2], [0, 0, 1]))
print(np.logical_or([0, 1, 2], [0, 0, 1]))
print(np.logical_not([0, 1, 2]))

[False False  True]
[False  True  True]
[ True False False]


In [46]:
# 是否有真
print(np.any([0, 0, 0]))
# 是否全真
print(np.all([1, 1, 1]))

False
True


In [53]:
arr = np.random.randint(20, 100, 10)
print(arr)
# where(条件,为真时的值,为假时的值)
print(np.where(arr >= 60, '及格', '补考'))
# select(条件列表,值列表,默认值)
print(np.select([arr < 60, (arr >= 60) & (arr < 80), arr >= 80], ['不及格', '良好', '优秀'], default='异常值'))

[26 88 67 23 96 72 98 35 40 78]
['补考' '及格' '及格' '补考' '及格' '及格' '及格' '补考' '补考' '及格']
['不及格' '优秀' '良好' '不及格' '优秀' '良好' '优秀' '不及格' '不及格' '良好']


## 4.排序函数

In [11]:
np.random.seed = 0
arr = np.random.randint(10, 20, 20)
# 返回新数组,不改变原数组
print(np.sort(arr))
# 改变原数组
arr.sort()
print(arr)

arr = np.random.randint(10, 100, 20)
# 去重并排序
print(np.unique(arr))

[10 10 10 11 12 12 12 12 13 13 13 13 14 14 14 15 15 15 18 19]
[10 10 10 11 12 12 12 12 13 13 13 13 14 14 14 15 15 15 18 19]
[11 13 30 33 60 67 74 85 88 90 91 92 94 95 98 99]


In [18]:
# 扩展
# 数组的拼接
arr1 = [1, 2, 3]
arr2 = [4, 5, 6]
print(np.concatenate((arr1, arr2)))

# 分割(必须能等分)
print(np.split(arr, 5))

# 调整形状(形状必须合法)
print(np.reshape(arr, [4, 5]))

[1 2 3 4 5 6]
[array([95, 85, 92, 91], dtype=int32), array([99, 98, 94, 13], dtype=int32), array([90, 60, 74, 88], dtype=int32), array([67, 98, 30, 11], dtype=int32), array([85, 11, 92, 33], dtype=int32)]
[[95 85 92 91 99]
 [98 94 13 90 60]
 [74 88 67 98 30]
 [11 85 11 92 33]]


# 三.numpy练习

In [28]:
"""
温度数据分析
某市一周的最高气温为[28,30,29,31,32,30,29]
- 计算平均,最高和最低气温
- 找出气温超过30度的天数
"""
temps = np.array([28, 30, 29, 31, 32, 30, 29])
print(temps)

print(f"平均气温:{np.mean(temps)}")
print(f"最高气温:{np.max(temps)}")
print(f"最低气温:{np.min(temps)}")

print("气温超过30度的天数:%s" % len(temps[temps > 30]))
print("气温超过30度的天数:%s" % np.cumsum(np.where(temps > 30, 1, 0))[-1])
print("气温超过30度的天数:%s" % np.count_nonzero(temps>30))

[28 30 29 31 32 30 29]
平均气温:29.857142857142858
最高气温:32
最低气温:28
气温超过30度的天数:2
气温超过30度的天数:2
气温超过30度的天数:2
